vsphere_user       = "administrator@vsphere.local"
vsphere_password   = "secret"
vsphere_server     = "x.x.x.x"
vsphere_datacenter = "Datacenter"
vsphere_cluster    = "Cluster"
host_hostname      = "x.x.x.x"
host_username      = "root"
host_password      = "secret"
